<?php

/**
 * @file
 * Primary module hooks for stchk34 module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

/**
 * Implements hook_theme().
 */
function stchk34_theme($existing, $type, $theme, $path) {
  return [
    'cat_page' => [
      'variables' => [
        'header' => NULL,
        'form' => NULL,
        'table' => NULL,
      ],
    ],
    'table-block' => [
      'variables' => [
        'cats_name' => NULL,
        'email' => NULL,
        'image' => NULL,
        'date' => NULL,
        'id' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_page_attachments().
 */
function stchk34_page_attachments(array &$attachments) {
  $attachments['#attached']['library'][] = 'stchk34/stchk34';
}
